name: worldtime_bloc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # injector koin
  koin: ^0.15.0-nullsaety.0
  koin_bloc: ^0.2.0-nuallsafety.0
  koin_flutter: ^0.11.0-nullsafety.0
  koin_test: ^0.13.0-nullsafety.0
  logger: ^1.0.0

  # 语法加强工具
  dartx: ^0.7.1
  dartz: ^0.9.2
  basics: ^0.6.0
  collection: ^1.15.0

  # 数据库、序列化、
  uuid: ^3.0.4
  freezed_annotation: ^0.14.0
  json_annotation: ^4.0.0
  freezed: ^0.14.0+2
  json_serializable: ^4.0.1

  #ui
  flutter_zoom_drawer: ^2.0.2
  percent_indicator: ^3.3.0-nullsafety.1

  # 路由
  auto_route: ^2.2.0
  auto_route_generator: ^2.1.0

  # 状态管理
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.17.0
  equatable: ^2.0.0
  pedantic: ^1.11.0
  rxdart: ^0.27.0

  # 动画
  animate_do: ^2.0.0
  simple_animations: ^3.1.1
  animations: ^2.0.0
  supercharged: ^2.0.0
  flutter_staggered_animations: ^1.0.0

  # 图片工具
  flutter_svg: ^0.22.0
  cached_network_image: ^3.0.0-nullsafety

  # 文本工具
  auto_size_text: ^3.0.0-nullsafety.0

  # 布局工具
  flextras: ^0.0.1+5
  styled_widget: ^0.3.1
  infinite_listview: ^1.1.0
  adaptive_breakpoints: any

  # 字体 & 图标
  unicons: ^2.0.1
  google_fonts: ^2.1.0

  # 键盘、form
  keyboard_actions: ^3.4.0

  # other
  rflutter_alert: ^2.0.2
  sized_context: 1.0.0-nullsafety

  # HTTP工具
  dio: ^4.0.0
  dio_cache_interceptor: ^2.3.0
  http: ^0.13.3
  retrofit: ^2.0.0
  cookie_jar: ^3.0.1
  fresh_dio: ^0.3.1
  dio_cookie_manager: ^2.0.0
  retrofit_generator: ^2.0.0
  vector_math: ^2.1.0
  dropdown_search: ^0.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.8
  test: ^1.16.8
  bloc_test: ^8.0.0
  build_runner: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
